name: "Mike Melnicki's Blog"
desc: "This is a placeholder for now"
markdown: redcarpet
pygments: true
relative_permalinks: true
permalink:     pretty

twitter:      mikemelnicki

# Sharing settings
sharing:
  twitter:    true
  facebook:   true
  gplus:      true
  hn:         true
