title:          "Mike Melnicki's Blog"
subtitle:       "This is a blog"
publisher:      "Mike Melnicki"
url:            http://blog.melnicki.com
logo:           logo.png
markdown:       redcarpet
pygments:       true

permalink:      pretty
twitter:        mikemelnicki
gplus:          115790104017468803673
relative_permalinks: true

# Sharing settings
sharing:
  twitter:    true
  facebook:   true
  gplus:      true
  hn:         true

# Analytics
analytics:
  google: true
  domain: melnicki.com
  analytics_id: 'UA-49046195-1'

# Google Fonts
# eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
google_font: 'Open+Sans:400,700,300'

disqus:
  # Eg. "exampleblog" Set to false to disable comments
  shortname:  melnicki
